## Creates duckdb versions of Contoso datasets {.unnumbered}


### Description

Creates duckdb versions of Contoso datasets



### Usage

<pre><code class='language-R'>create_contoso_duckdb(db_dir = c("in_memory"), size = "100K")
</code></pre>


### Arguments

<table role = "presentation">
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="db_dir">db_dir</code></td>
<td>
&quot;temp&quot; or &quot;in_memory&quot;
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="size">size</code></td>
<td>
&quot;100k&quot;,&quot;1M&quot; or &quot;10M&quot;
</td></tr>
</table>


### Details

The [create_contonso_duckdb] function registers the following Contoso datasets as DuckDB tables:
- 'sales': Contains sales transaction data.
- 'product': Contains details about products, including attributes like product name, manufacturer, and category.
- 'customer': Contains customer demographic and geographic information.
- 'store': Contains information about store locations and attributes.
- 'fx': Contains foreign exchange rate data for currency conversion.
- 'date': Contains various date-related information, including day, week, month, and year.

You can choose to store the database in memory or in a temporary directory. If you choose &quot;temp&quot;, the database will be created in a temporary file on disk. If you choose &quot;in_memory&quot;, the database will be created entirely in memory and will be discarded after the R session ends.



### Value

A list of lazy 'tbl' objects that are references to the Contoso datasets stored in the DuckDB database. The list contains the following tables:
- 'sales'
- 'product'
- 'customer'
- 'store'
- 'fx'
- 'store'
- 'orderrows'
- 'date'



### Examples
```{r, warning=FALSE, message=FALSE, eval=FALSE}
library("contoso")

# Create a DuckDB version of Contoso datasets stored in memory

 create_contoso_duckdb(db_dir = "in_memory",size="100K")



```
